{% set name = "poe-api-wrapper" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poe-api-wrapper-{{ version }}.tar.gz
  sha256: 592e187287f82e1a2cf49a5ebffeeefc2b2d030d9223de96a8cba3e7ce76c307

build:
  entry_points:
    - poe = poe_api_wrapper.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cloudscraper
    - websocket-client
    - requests-toolbelt
    - loguru
    - rich ==13.3.4

test:
  imports:
    - poe_api_wrapper
  commands:
    - pip check
    - poe --help
  requires:
    - pip

about:
  home: https://github.com/snowby666/poe-api-wrapper
  summary: A simple, lightweight and efficient API wrapper for Poe.com
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pedrohgmacedo
